### ISSUE TITLE
Request for /robots.txt

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/wordpress-website-lifecycle#21]
The only place there any "robots" variable gets a value is at
https://github.com/WordPress/WordPress/blob/fd6357ae7bde138ecfd7b24969ed19d013d9b6d3/wp-includes/class-wp-query.php#L804-L805

@johnbillion Could you help me how core detects `/robots.txt` requests?

**Comment by johnbillion** [comment]
https://github.com/johnbillion/wordpress-develop/blob/5824f4cbba0b13d043f03f9eeff7c4a4197a5006/src/wp-includes/class-wp-rewrite.php#L1285

**Comment by szepeviktor** [comment]
Thank you, John!
You are my most valuable secret agent.
